before:
  hooks:
    - go mod tidy
builds:
  - binary: client
    env:
      - CGO_ENABLED=0
    main: ./cmd/client.go
    goos:
      - linux
      - windows
      - darwin
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w -X github.com/DVKunion/SeaMoon/pkg/consts.Version=1.0.0
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'